#!/bin/bash

#backup scrip for /var /etc filesystem


filename=`date +'%d%m%y'`

echo $filename

tar cvf /tmp/backup$filename.tar /var /etc

gzip /tmp/backup$filename.tar

#Now going to verify the backup status

find /tmp/backup$filename.tar.gz -mtime -1 -type f -print &> /dev/null

        if [ $? -eq 0 ]

        then

                echo backup and archive succesfull

# now going to  move the backup file to another nas drive or path
#sshpass is the command to skip the password section while during "scp" command execute,
#so we need to install sshpass package using  " yum install sshpass"

        sshpass -p "nnnn" scp /tmp/backup$filename.tar.gz root@192.168.1.25:/root/shellscript/


                echo File moved to storage

        if [ $? -eq 0 ]

        then

                rm -rf /tmp/backup$filename.tar.gz

        fi
 else

                echo backup failled

        fi
