#!/bin/bash

# copy the file to remote host

        for i in 192.168.1.25 192.168.1.26 192.168.1.27
        do
                sshpass -p "nnnn" scp /root/proscript/* root@192.168.1.25:/home/nava/.
        done


file=`cat /root/proscript/hostname`

        for n in $file

        do
                 sshpass -p "nnnn" scp /root/proscript/* root@192.168.1.25:/home/arun/.
        done
