#!/bin/bash

#Script delete files 90days old

rm -rf /root/proscript/old.txt

find /root/proscript -mtime +90 -exec ls -l {} \; > /root/proscript/old.txt

find /root/proscript -mtime +90 -exec mv {} {}$(date +'%d%m%y') \;

mkdir /root/proscript/Oldfiles

find /root/proscript -mtime +90 -exec mv {} /root/proscript/Oldfiles/. \;

zip Oldfdele$(date +'%d%m%y').zip ./Oldfiles/*

rm -rf ./Oldfiles

